<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="stylesheet" href="/styles.css">
</head>

<body class="about-page">
        <nav>
                <a href="/characters/about">About</a>
                <a href="/characters/all">Home</a>
				<a href="/characters/add">Add Character</a>
        </nav>

        <section class="about">
            <img src="/image/bio.jpeg" alt="IsabelBarboza"  width="104" height="142">
            <h1>About this website</h1>

            <p>
            My name is <strong>Isabel Barboza</strong>, I am 26 years old, and I have been a Dota 2 fan since around 2016.
            A high school friend introduced me to the game, and it quickly became my favorite.
            </p>

            <p>
            Even though my rank medal is not very high, I am very passionate about Dota 2.
            I enjoy learning from every match, improving my skills, and understanding the strategy behind the game.
            </p>

            <p>
            I created this website as part of my <strong> Software Engineering course at UNCG</strong>.
            While building this site, I practiced writing HTML structure, styling with CSS, and thinking about layout and design.
            This project helps me improve my technical skills while working on a topic that motivates me.
            </p>

            <p>
            I chose a <strong> dark and bold design </strong> with strong visual elements because I wanted the site to feel powerful and immersive,
            similar to the atmosphere of Dota 2. The colors and style reflect intensity, focus, and strong character identity.
            </p>
            
          <blockquote>
                <p>
                    <em>
                        This website represents both who I am as a gamer and my <strong>growth</strong> as a software development student.
                    </em>
                </p>
            </blockquote>

        </section>
    </body>
</html>